import type { Extension } from '@odh-dashboard/plugin-core';

// This file gets auto-generated by the build process (GenerateExtensionsPlugin).
// The virtual module replaces this stub at webpack compile time.
const pluginExtensions: Record<string, Extension[]> = {};

export default pluginExtensions;
